Refactor/detail/add detail
coconut-thisABLE/thisABLE_front_2 pull request #11
Opened 2022-11-06 03:27 UTC by seohyun319

- refactor Detail
- make FacilitiesIcons component from PlaceInfo
- set ReviewAverageCount data
- set toggleView using Accordian
- #8 

![image](https://user-images.githubusercontent.com/76686872/200152127-264951d8-cfbf-4b9b-aa89-87e3835d905c.png)

TODO
- make reviewAverage to starView
- review CR

2022-11-07 08:47 UTC, nami-koko requested changes

2022-11-07 08:47 UTC, nami-koko commented on components/common/FacilitiesIcons.tsx
> +      <Image src={src} width={size} height={size} />
alt 빠졌어요

2022-11-07 08:47 UTC, nami-koko commented on components/common/FacilitiesIcons.tsx
> +  hasDescription: boolean
boolean이면 default value를 false로 놓고 true일때만 props를 쓰는것도 나쁘지 않아보여요. 
그리고 props type 따로 빼서 쓰기로 했었는데 baseLayout 참고해주세욥

2022-11-07 08:47 UTC, nami-koko commented on components/common/ToggleView.tsx
> +  const [expanded, setExpanded] = React.useState<string | false>(false)
모듈에서 useState만 가져오지 않고 이렇게 쓰는 이유가 있을까요? 그리고 type 지정에에선 <string | boolean>이 맞을거같은데 false 쓰신 이유도 궁금해요. boolean 이니까 isExpanded 어떤가요?

2022-11-07 08:47 UTC, nami-koko commented on components/common/ToggleView.tsx
> +      expanded={expanded === 'panel1'}
```  
const [expanded, setExpanded] = React.useState<boolean>(false)
  
  return (
    <Accordion
      expanded={expanded}
      onChange={() => setExpanded(!expanded)}
    >
```

이렇게 하면 handleChange 함수 안쓰고 가능한데 어떨까요?

2022-11-07 08:47 UTC, nami-koko commented on types/index.ts
> +  _id: number
list 반복문 에러 해결때문에 number로 바뀐건가요?? 백에 업뎃 해줘야 하는거면 알려주세욥

2022-11-07 08:47 UTC, nami-koko commented on components/common/Text.tsx
> +export const StyledText = styled.div<TextType>`
text니까 div보다는 p태그가 나을거같아요

2022-11-07 09:24 UTC, seohyunPang commented on components/common/ToggleView.tsx
> +  const [expanded, setExpanded] = React.useState<string | false>(false)
mui 기본 코드 그대로 써서 그래요 ^-^... 좋은 것 같아요 고치겠습니다~

2022-11-07 09:28 UTC, seohyun319 commented on components/common/ToggleView.tsx
> +  const [expanded, setExpanded] = React.useState<string | false>(false)
mui 기본 코드 그대로 써서 그래요 ^-^... 좋은 것 같아요 고치겠습니다~

2022-11-07 14:55 UTC, seohyun319 commented on types/index.ts
> +  _id: number
기존의 스웨거 파일 받기 전(==변경 전 초기)의 더미 데이터로 작업했던 거라 그래요! 현재 스웨거에는 number로 돼있어서 그거에 맞게 고쳤습니다

2022-11-20 13:20 UTC, nami-koko approved these changes

2022-11-20 13:44 UTC, merged