Refactor/home/add-map-and-list
coconut-thisABLE/thisABLE_front_2 pull request #13
Opened 2022-11-26 11:40 UTC by nami-koko

2022-11-26 14:51 UTC, seohyun319 requested changes

2022-11-26 14:51 UTC, seohyun319 commented on api/usePlaceListQuery.ts
> +      `${process.env.NEXT_PUBLIC_BASE_URL}/?latitude=37.5441270&longitude=126.9667812&page=${pageNumber}`
baseUrl 다음 경로를 변수로 받는 fetch 함수로 빼두면 추후 사용하기 좋을 것 같아요!
fetchApi 함수를 만들고 -> 그 함수를 사용하는 fetchPlaces 함수를 만들어 fetchPlaces 함수에서 pageNumber를 변수로 받는 식

2022-11-26 14:51 UTC, seohyun319 commented on components/detail/index.tsx
> +import { useRouter } from 'next/router'
작성한 파일 말고 라이브러리에서 불러오는 import문은 최상단으로 올려주시면 좋을 것 같습니다!

2022-11-26 14:51 UTC, seohyun319 commented on components/common/PlaceList.tsx
> +import { useState } from 'react'
import 순서 next -> react -> styled -> types -> api -> 공통 컴포넌트 -> 개별 컴포넌트
순으로 정해보는 건 어떨까요?

2022-11-26 14:51 UTC, seohyun319 commented on components/common/PlaceList.tsx
> +  const [showDetail, setShowDetail] = useState<boolean>(false)
bool형 네이밍 동사 원형 쓸 때는 3인칭 단수로 써 주세요! `showsDetail`

2022-11-26 14:51 UTC, seohyun319 commented on components/common/PlaceList.tsx
> +            router.pathname !== '/'
특별한 이유가 있는 게 아니라면 조건문은 긍정문인 게 바로 이해하기 편할 것 같습니다. 
```js
router.pathname == '/'
    ? setShowDetail(true)
    : router.push(`detail/${place._id}`)
```

2022-11-26 15:07 UTC, nami-koko commented on api/usePlaceListQuery.ts
> +      `${process.env.NEXT_PUBLIC_BASE_URL}/?latitude=37.5441270&longitude=126.9667812&page=${pageNumber}`
apiClient 만들어서 base url 지정하면 함수 따로 만들필요 없이 뒤에 경로만 붙이면 되는데, axios.create로 만든 api client에서 보내는 요청에는 CORS 에러가 떠서 일단 이렇게 처리해뒀어요!

2022-11-26 15:10 UTC, nami-koko commented on components/common/PlaceList.tsx
> +import { useState } from 'react'
오 좋아요~! 매번 직접 정리하는건 비효율적일거같은데 eslint-plugin-import로 설정해서 쓰는게 좋을까요?

2022-11-26 15:16 UTC, seohyun319 commented on components/common/PlaceList.tsx
> +import { useState } from 'react'
네 좋아요~~

2022-11-26 15:25 UTC, seohyun319 commented
로컬에서 직접 돌려보니까 
1. `/`에서 대략적으로 1096px 넘어가면 width가 남아서 오른쪽 여백이 생깁니다 
2. 요 에러 무시해도 되는 건가요? 
    ```
    TypeError: Failed to fetch
        at __webpack_require__.hmrM (http://localhost:3000/_next/static/chunks/webpack.js?ts=1669475356234:1174:20)
    error - unhandledRejection: Error: aborted
    ```
3. 지도 위의 아무 요소를 한 번 클릭하면 무조건 디테일 페이지로 넘어가고, 그 다음부터는 디테일 페이지에서 '뒤로가기' 버튼이 작동하지 않아요

2022-11-26 15:32 UTC, seohyun319 commented on components/home/MapAndList.tsx
> +        <Detail setShowDetail={setShowDetail} />
상하위 컴포넌트에 동일한 useState 변수인 showDetail를 두 번 선언하는 것보다는 callback 함수로 처리하는 게 나을 것 같아요

2022-11-26 16:01 UTC, nami-koko commented on components/home/MapAndList.tsx
> +        <Detail setShowDetail={setShowDetail} />
네 좋아요~~! 위 코멘트에 reply가 안되네요
1. 확인해서 수정해둘게요
2. 저한텐 에러가 안뜨는데 언제 뜨는 에러인가요?? 빌드?
<img width="1719" alt="스크린샷 2022-11-27 오전 12 57 19" src="https://user-images.githubusercontent.com/86053064/204097574-5730a9d2-09d8-41fc-ab13-66ead247709e.png">
3. 홈 화면에서 지도에 아무거나 클릭하면 오른쪽에 컴포넌트 변경이 아니라 디테일 페이지로 넘어가는건가요?? 작동하지 않는 버튼이면 숨김처리 하는게 맞을거같아요

2022-11-28 13:48 UTC, seohyun319 commented on components/home/MapAndList.tsx
> +        <Detail setShowDetail={setShowDetail} />
2. yarn run dev로 돌렸을 때 터미널에 떠요!
3. 지도 아무거나 클릭했을 때 오른쪽 컴포넌트가 변경되고, '뒤로 가기'가 먹히지 않는 거 보면 정상적인 상황은 아닌 것 같아요 (리스트뷰에서 하나 눌러서 상세정보로 뷰가 바뀔 땐 '뒤로 가기' 정상 작동 합니다)

2022-12-05 11:53 UTC, seohyun319 approved these changes
👍

2022-12-05 12:31 UTC, merged