Refactor/map/add map
coconut-thisABLE/thisABLE_front_2 pull request #9
Opened 2022-10-04 07:12 UTC by nami-koko

- add global button styles
- add map component
<img width="1440" alt="스크린샷 2022-10-04 오후 4 09 16" src="https://user-images.githubusercontent.com/86053064/193756891-dd1b83bc-4300-4d1d-9165-16a33cc28ef9.png">

<img width="1039" alt="스크린샷 2022-10-04 오후 4 12 01" src="https://user-images.githubusercontent.com/86053064/193757142-32489d7f-8370-48b1-937f-dc885cd9b8f0.png">

TODO
- add renderMarker and placeInfo
- fix filter styles for mobile size

2022-10-04 13:48 UTC, seohyun319 requested changes

2022-10-05 07:16 UTC, nami-koko commented on components/map/index.tsx
> +const Map = () => {
넵 파일명은 소문자로 쓰는게 일반적인거같아서 의도했어요 그대로 두겠습니다~!

2022-10-05 07:18 UTC, nami-koko commented on components/map/index.tsx
> +    title: 'Disabled Toilet',
여러 페이지에서 겹치는 텍스트 있으면 어떻게 번역할건지 통일 필요해보이는데, 기존 레포의 화면은 에러때문에 띄울수가 없어서 제가 확인할 수가 없네요..! 작업하면서 각자 임의로 번역하기보단 코드/화면 보면서 같이 통일하고 바꿔야할거같아요

2022-10-05 07:35 UTC, merged

2022-10-05 09:22 UTC, seohyun319 commented on components/map/index.tsx
> +    title: 'Disabled Toilet',
텍스트는 피그마와 동일할 건데, 
https://github.com/coconut-thisABLE/thisABLE_front/commit/83988a352839919389d11dd9473b93788919319a
원래 쭉 한글로 개발하다가 한 번에 영어로 바꾼 커밋인데 이거 참고하면서 하시면 좋을 것 같습니다!  @nami-koko